Clarify setting of `git_branch` in Matchfile
Until I set `git_branch` to a branch that didn't yet exist, I got the following cryptic error:

/Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:115:in `block in branch_exists?': [!] undefined method `shellescape' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:114:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:114:in `branch_exists?'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:89:in `checkout_branch'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:17:in `clone'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/change_password.rb:7:in `update'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/git_helper.rb:21:in `clone'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/runner.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/commands_generator.rb:121:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/lib/match/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.0/bin/match:6:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'