Use correct spelling of icloud service (#11861)
This caused previously `icloud' for "NoMethodError: [!] undefined method `icloud' for Spaceship::Portal::AppService:Class".