Fix undefined local variable or method `keychain_path'
Since https://github.com/fastlane/fastlane/commit/b9ceba3814a53f600557f2357c5fcc9b032ed8ab, calling `sigh resign` fails with:

```...gems/sigh-1.10.0/lib/sigh/resign.rb:10:in `run': [!] undefined local variable or method `keychain_path' for #<Sigh::Resign:0x007fcb418d8358>```

This is caused of course by `keychain_path` not being parsed from the args appropriately in `run`. This PR fixes that :)