Use correct spelling of icloud service
This caused previously `icloud' for "NoMethodError: [!] undefined method `icloud' for Spaceship::Portal::AppService:Class".