Get Activity of a View if the Context is a ContextWrapper
In some cases calling View.getContext will return a ContextWrapper instead
of an Activity. This will cause a ClassCastException:

```
java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
at tools.fastlane.screengrab.Screengrab$1.perform(Screengrab.java:77)
```

The added code is based on [this Stackoverflow answer](http://stackoverflow.com/a/27434760/111777).