Update `fakefs` to fix test failures on Ruby 3.2.2 (#21588)
* Update fakefs from 1.2 to 1.9

To fix failure on `bundle exec rspec` in Ruby 3.2.2

We kept having "NameError: undefined method `=~' for class `FakeFS::Pathname'" errors when running the tests in Ruby 3.2.2 on our Macs

* Use fakefs 1.8

As fakefs 1.9+ requires Ruby 2.7 while fastlane's gemspec still officially supports 2.6